### PR TITLE
Update to latest version of Rust Nightly + Dependency Updates

### PR DESCRIPTION
**Pull request by LunaticWyrm467**
Hi there!
I saw this fantastic crate and I tried to use it on the latest version of rust, only to notice that this crate failed to compile due to a few issues, such as some outdated crates failing to run.
So, I took the liberty of pushing out a pull request with the dependencies updated for you, and also I switched back to the original `packed_simd` crate.

This was checked and tested on rust `1.76.0-nightly`.
Oh, and I added the `Clone` derive to a few types to allow for better compatibility with some types, so some key types could be included in wrapper structs that derive from `Clone`.

### CODE REVIEW

**Comment by velvia** [comment]
Hey @LunaticWyrm467 thank you so much.   I had started working on another PR that was trying to update the build but couldn't get that one to build.   Too many distractions!   

I approved the build and it seems to fail, but it also seems to be trying to build on stable.  Weird.
Let me pull this locally and try it out.

**Comment by velvia** [comment]
Oh, the `rust-toolchain` was deleted.  Say would you mind updating it to 1.76.0-nightly?  That's likely why the CI fails.

**Comment by LunaticWyrm467** [comment]
Yeah, I removed it in favor of a cargo version override while testing, mostly because I had issues on my end getting it to build initially. Looks like I may have forgotten to add it back, I'll do that when I get the chance!

**Comment by LunaticWyrm467** [comment]
Try that. Let me know if anything else fails.

**Comment by velvia** [comment]
Thanks @LunaticWyrm467 .... the tests seem to pass but the doctests fail.  Actually they look more like compile failures than doctest failures, it's very weird.... I'll see if I have time to look into it.

https://github.com/velvia/compressed-vec/actions/runs/7142826807/job/19472246385?pr=6

**Comment by LunaticWyrm467** [comment]
Huh. strange. Well, if you need any help, let me know.

**Comment by velvia** [comment]
They are doctest errors.  I'll merge and then fix later.  Thanks again.

**Comment by LunaticWyrm467** [comment]
Thank you!

**Pull request merged**
